# FindQt.cmake - Wrapper for Qt6 when O3DE_QT_VERSION=6
# Provides find_package(Qt) compatibility and Qt6-native helper functions

find_package(Qt6 REQUIRED COMPONENTS Core Gui Widgets Svg SvgWidgets Xml Concurrent Network OpenGL PrintSupport)

set(Qt_FOUND TRUE)
set(Qt_VERSION ${Qt6_VERSION})
set(QT_VERSION_MAJOR 6)

foreach(_module Core Gui Widgets Svg SvgWidgets Xml Concurrent Network OpenGL PrintSupport)
    if(NOT TARGET Qt::${_module})
        add_library(Qt::${_module} INTERFACE IMPORTED)
        target_link_libraries(Qt::${_module} INTERFACE Qt6::${_module})
    endif()
    if(NOT TARGET 3rdParty::Qt::${_module})
        add_library(3rdParty::Qt::${_module} INTERFACE IMPORTED)
        target_link_libraries(3rdParty::Qt::${_module} INTERFACE Qt6::${_module})
    endif()
endforeach()

find_package(Qt6 COMPONENTS OpenGLWidgets QUIET)
find_package(Qt6 COMPONENTS Test QUIET)
if(NOT TARGET 3rdParty::Qt::Test)
    add_library(3rdParty::Qt::Test INTERFACE IMPORTED)
endif()

foreach(_optional_module SvgWidgets OpenGLWidgets Test Concurrent Network OpenGL PrintSupport)
    if(TARGET Qt6::${_optional_module})
        if(NOT TARGET Qt::${_optional_module})
            add_library(Qt::${_optional_module} INTERFACE IMPORTED)
            target_link_libraries(Qt::${_optional_module} INTERFACE Qt6::${_optional_module})
        endif()
        if(NOT TARGET 3rdParty::Qt::${_optional_module})
            add_library(3rdParty::Qt::${_optional_module} INTERFACE IMPORTED)
            target_link_libraries(3rdParty::Qt::${_optional_module} INTERFACE Qt6::${_optional_module})
        endif()
    endif()
endforeach()

find_package(Qt6 COMPONENTS Tools LinguistTools QUIET)
if(TARGET Qt6::uic)
    # Use the Qt6 tools so generated files match the Qt6 APIs
    set(QT_UIC_EXECUTABLE Qt6::uic CACHE FILEPATH "Qt6 uic executable" FORCE)
    set(QT_MOC_EXECUTABLE Qt6::moc CACHE FILEPATH "Qt6 moc executable" FORCE)
    set(QT_RCC_EXECUTABLE Qt6::rcc CACHE FILEPATH "Qt6 rcc executable" FORCE)
else()
    set(QT_UIC_EXECUTABLE /usr/lib/qt6/uic CACHE FILEPATH "Qt6 uic executable" FORCE)
    set(QT_MOC_EXECUTABLE /usr/lib/qt6/moc CACHE FILEPATH "Qt6 moc executable" FORCE)
    set(QT_RCC_EXECUTABLE /usr/lib/qt6/rcc CACHE FILEPATH "Qt6 rcc executable" FORCE)
endif()

# lrelease/lupdate must be real file paths because they get copied as runtime dependencies
if(TARGET Qt6::lrelease)
    get_target_property(_qt_lrelease_path Qt6::lrelease LOCATION)
else()
    set(_qt_lrelease_path "")
endif()
if(NOT _qt_lrelease_path)
    find_program(_qt_lrelease_path NAMES lrelease-qt6 lrelease HINTS /usr/lib/qt6 /usr/lib/qt6/bin)
endif()
if(NOT _qt_lrelease_path)
    set(_qt_lrelease_path /usr/bin/lrelease)
endif()
set(QT_LRELEASE_EXECUTABLE ${_qt_lrelease_path} CACHE FILEPATH "Qt lrelease executable" FORCE)
unset(_qt_lrelease_path)

if(TARGET Qt6::lupdate)
    get_target_property(_qt_lupdate_path Qt6::lupdate LOCATION)
else()
    set(_qt_lupdate_path "")
endif()
if(NOT _qt_lupdate_path)
    find_program(_qt_lupdate_path NAMES lupdate-qt6 lupdate HINTS /usr/lib/qt6 /usr/lib/qt6/bin)
endif()
if(NOT _qt_lupdate_path)
    set(_qt_lupdate_path /usr/bin/lupdate)
endif()
set(QT_LUPDATE_EXECUTABLE ${_qt_lupdate_path} CACHE FILEPATH "Qt lupdate executable" FORCE)
unset(_qt_lupdate_path)

function(ly_qt_uic_target TARGET)
    get_target_property(all_ui_sources ${TARGET} SOURCES)
    list(FILTER all_ui_sources INCLUDE REGEX "^.*\\.ui$")
    if(NOT all_ui_sources)
        message(FATAL_ERROR "Target ${TARGET} contains AUTOUIC but doesnt have any .ui file")
    endif()

    if(AUTOGEN_BUILD_DIR)
        set(gen_dir ${AUTOGEN_BUILD_DIR})
    else()
        set(gen_dir ${CMAKE_CURRENT_BINARY_DIR}/${TARGET}_autogen/include)
    endif()

    foreach(ui_source ${all_ui_sources})
        get_filename_component(filename ${ui_source} NAME_WE)
        get_filename_component(dir ${ui_source} DIRECTORY)
        if(IS_ABSOLUTE ${dir})
            file(RELATIVE_PATH dir ${CMAKE_CURRENT_SOURCE_DIR} ${dir})
        endif()
        set(outfolder ${gen_dir}/${dir})
        set(outfile ${outfolder}/ui_${filename}.h)
        get_filename_component(infile ${ui_source} ABSOLUTE)
        file(MAKE_DIRECTORY ${outfolder})
        add_custom_command(OUTPUT ${outfile}
            COMMAND ${QT_UIC_EXECUTABLE} -o ${outfile} ${infile}
            MAIN_DEPENDENCY ${infile} VERBATIM
            COMMENT "UIC ${infile}"
        )
        set_source_files_properties(${infile} PROPERTIES SKIP_AUTOUIC TRUE)
        set_source_files_properties(${outfile} PROPERTIES SKIP_AUTOMOC TRUE SKIP_AUTOUIC TRUE GENERATED TRUE)
        list(APPEND all_ui_wrapped_sources ${outfile})
    endforeach()

    target_sources(${TARGET} PRIVATE ${all_ui_wrapped_sources})
    source_group("Generated Files" FILES ${all_ui_wrapped_sources})

    get_property(has_includes TARGET ${TARGET} PROPERTY INCLUDE_DIRECTORIES SET)
    if(has_includes)
        get_property(all_include_directories TARGET ${TARGET} PROPERTY INCLUDE_DIRECTORIES)
        foreach(dir ${all_include_directories})
            if(IS_ABSOLUTE ${dir})
                file(RELATIVE_PATH dir ${CMAKE_CURRENT_SOURCE_DIR} ${dir})
            endif()
            list(APPEND new_includes ${gen_dir}/${dir})
        endforeach()
    endif()
    list(APPEND new_includes ${gen_dir})
    target_include_directories(${TARGET} PRIVATE ${new_includes})
endfunction()

function(ly_add_translations)
endfunction()

